apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: kube-system
subsets:
- addresses:
  - ip: 172.16.118.50
  - ip: 172.16.118.52
  - ip: 172.16.118.55
  ports:
  - name: http-metrics
    port: 10249
    protocol: TCP
