---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dingtalk
  name: webhook-dingtalk
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dingtalk
  template:
    metadata:
      labels:
        run: dingtalk
    spec:
      containers:
        - name: dingtalk
          image: registry.cn-hangzhou.aliyuncs.com/jie_yan/monitoring-prometheus-webhook-dingtalk:v0.3.0
          imagePullPolicy: IfNotPresent
          args:
            - --ding.profile=webhook1=https://oapi.dingtalk.com/robot/send?access_token=XXXX
          ports:
            - containerPort: 8060
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: dingtalk
  name: webhook-dingtalk
  namespace: monitoring
spec:
  ports:
    - port: 8060
      protocol: TCP
      targetPort: 8060
  selector:
    run: dingtalk
  sessionAffinity: None